name: hidePlayer
version: '0.1'
main: org.hideplayer.HidePlayer
api-version: '1.20'
softdepend: [SkinsRestorer, PlaceholderAPI]

commands:
  hideplayer:
    description: "Main command of HidePlayer"
    aliases: [hp]
    usage: /hideplayer <subcommand>
